import json
from collections import Counter   # Counter helps us keep track of counts

# File paths
BIAS_FILE = "bias_words.txt"                     # file containing the bias words
PRED_FILE = "output/predictions.json"            # predictions generated by the model
GT_FILE = "audio/ground_truth/84-121123.trans.txt"  # ground truth transcripts


# -------------------- LOAD BIAS WORDS --------------------

# Open the bias words file and store the words in a set
# Using a set makes searching faster
with open(BIAS_FILE) as f:
    bias_words = set(w.strip().lower() for w in f if w.strip())


# -------------------- LOAD MODEL PREDICTIONS --------------------

# Load predicted transcripts from the JSON file
with open(PRED_FILE) as f:
    preds = json.load(f)


# -------------------- LOAD GROUND TRUTH --------------------

# Dictionary to store actual transcripts for each audio file
gt = {}

with open(GT_FILE) as f:
    for line in f:
        # Each line format: audioID sentence
        k, v = line.strip().split(" ", 1)

        # Add ".wav" because our prediction files use wav filenames
        gt[k + ".wav"] = v.lower()


# Counter to track total and correct bias word predictions
stats = Counter()


# -------------------- COMPARE PREDICTIONS --------------------

# Loop through each audio file in the ground truth
for wav in gt:

    # Skip if prediction for this file does not exist
    if wav not in preds:
        continue

    # Convert sentences into sets of words
    gt_words = set(gt[wav].split())
    pred_words = set(preds[wav].split())

    # Check each bias word
    for word in bias_words:

        # If this bias word actually appears in the ground truth
        if word in gt_words:

            # Count it as a total bias word occurrence
            stats["total"] += 1

            # If the model predicted it correctly
            if word in pred_words:
                stats["correct"] += 1


# -------------------- CALCULATE ACCURACY --------------------

# Accuracy = correctly predicted bias words / total bias words
print("Bias-word accuracy:",
      stats["correct"] / stats["total"] if stats["total"] else 0)