import json
import pandas as pd
from jiwer import wer, cer   # jiwer library helps us calculate WER and CER

# File paths
PRED_FILE = "output/predictions.json"                 # model predictions
GT_FILE = "audio/ground_truth/84-121123.trans.txt"    # actual ground truth transcripts


# -------------------- LOAD MODEL PREDICTIONS --------------------

# Open the JSON file containing predictions generated by the Vosk model
with open(PRED_FILE) as f:
    predictions = json.load(f)


# -------------------- LOAD GROUND TRUTH --------------------

# Dictionary to store actual transcripts for each audio file
ground_truth = {}

with open(GT_FILE) as f:
    for line in f:
        # Each line format:  audioID sentence
        parts = line.strip().split(" ", 1)

        # Make sure the line has both audio id and sentence
        if len(parts) == 2:
            # Add ".wav" because prediction files use wav filenames
            ground_truth[parts[0] + ".wav"] = parts[1].lower()


# List to store error metrics for each file
rows = []


# -------------------- CALCULATE ERROR METRICS --------------------

# Loop through each predicted file
for wav, pred in predictions.items():

    # Skip files that don't exist in ground truth
    if wav not in ground_truth:
        continue

    # Get the correct transcript
    gt = ground_truth[wav]

    # Convert prediction to lowercase for fair comparison
    pred = pred.lower()

    # Store error metrics for this audio file
    rows.append({
        "file": wav,                 # audio file name
        "WER": wer(gt, pred),        # Word Error Rate
        "CER": cer(gt, pred),        # Character Error Rate
        "ground_truth": gt,          # actual sentence
        "prediction": pred           # predicted sentence
    })


# -------------------- SAVE RESULTS --------------------

# Convert results into a pandas dataframe
df = pd.DataFrame(rows)

# Save the dataframe as a CSV file for analysis
df.to_csv("output/error_metrics.csv", index=False)


# Print completion message
print("Error analysis DONE using the actual transcripts and transcripts generated by VOSK model")